"""
AI Interactive System - Powered by Ollama (local LLM)
------------------------------------------------------
- Speak  -> system listens and transcribes
- Camera scans face -> YES/NO detection
- All responses generated by llama3 via Ollama (fully local)

REQUIREMENTS:
    pip install SpeechRecognition pyaudio opencv-python Pillow requests
    ollama must be running:  ollama serve
"""

import tkinter as tk
from tkinter import scrolledtext
import threading
import time
import re
import queue
import datetime
import json

try:
    import requests
    REQUESTS_OK = True
except ImportError:
    REQUESTS_OK = False

try:
    import speech_recognition as sr
    SPEECH_OK = True
except ImportError:
    SPEECH_OK = False

try:
    import cv2
    CAM_OK = True
except ImportError:
    CAM_OK = False


# ══════════════════════════════════════════════
#  OLLAMA CLIENT
# ══════════════════════════════════════════════
OLLAMA_URL   = "http://localhost:11434/api/chat"
OLLAMA_MODEL = "llama3"

SYSTEM_PROMPT = """You are a local AI assistant running on the user's machine with no internet access.
You have access to a camera and microphone.

Your behaviour:
- When the user asks if you can see them, you will be told the camera result (face detected or not) and you must respond with YES or NO first, then explain briefly.
- When asked "who am I", always respond that the user is "Admin" with full access.
- For math problems, solve them step by step and show your working.
- For code problems or bugs, analyse the code, identify the issue, and suggest a fix.
- For logic problems or ethical dilemmas (like survival scenarios), reason through all angles - utilitarian, deontological, and practical - then give a clear conclusion.
- For general questions, give a direct, helpful, reasoned answer.
- Keep responses clear and concise. Do not use emojis or special symbols.
- Always respond in plain text only. No markdown, no bullet symbols, no asterisks.
- Use dashes (-) for lists if needed. Use plain text headings in ALL CAPS."""


def query_ollama(messages, callback_chunk):
    """
    Stream a response from Ollama.
    callback_chunk(text) is called for each streamed chunk.
    Returns the full response text.
    """
    if not REQUESTS_OK:
        err = "requests library not installed. Run: pip install requests"
        callback_chunk(err)
        return err

    payload = {
        "model":    OLLAMA_MODEL,
        "messages": messages,
        "stream":   True,
    }

    full_response = []
    try:
        with requests.post(OLLAMA_URL, json=payload, stream=True, timeout=120) as resp:
            if resp.status_code != 200:
                err = "Ollama error: " + str(resp.status_code) + " - Is ollama running? Run: ollama serve"
                callback_chunk(err)
                return err

            for raw_line in resp.iter_lines():
                if not raw_line:
                    continue
                try:
                    data = json.loads(raw_line)
                    chunk = data.get("message", {}).get("content", "")
                    if chunk:
                        full_response.append(chunk)
                        callback_chunk(chunk)
                    if data.get("done"):
                        break
                except json.JSONDecodeError:
                    pass

    except requests.exceptions.ConnectionError:
        err = ("\nCannot connect to Ollama.\n"
               "Make sure Ollama is running by opening a terminal and running:\n"
               "    ollama serve\n"
               "Then try again.")
        callback_chunk(err)
        return err

    return "".join(full_response)


# ══════════════════════════════════════════════
#  CAMERA - FACE DETECTION
# ══════════════════════════════════════════════
class Camera:
    def __init__(self):
        self.cap           = None
        self.face_detected = False
        self.running       = False
        self.frame         = None
        self.cascade       = None
        self.cascade_alt   = None

        if CAM_OK:
            self.cascade = cv2.CascadeClassifier(
                cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
            self.cascade_alt = cv2.CascadeClassifier(
                cv2.data.haarcascades + 'haarcascade_frontalface_alt2.xml')

    def start(self):
        if not CAM_OK:
            return
        for idx in range(3):
            cap = cv2.VideoCapture(idx)
            if cap.isOpened():
                self.cap = cap
                break
        if self.cap is None:
            return

        self.cap.set(cv2.CAP_PROP_FRAME_WIDTH,  640)
        self.cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
        self.running = True
        threading.Thread(target=self._loop, daemon=True).start()

    def _loop(self):
        while self.running:
            ret, frame = self.cap.read()
            if not ret:
                time.sleep(0.05)
                continue

            display = cv2.resize(frame, (640, 480))
            gray    = cv2.cvtColor(display, cv2.COLOR_BGR2GRAY)
            gray    = cv2.equalizeHist(gray)

            faces = self.cascade.detectMultiScale(
                gray, scaleFactor=1.05, minNeighbors=3,
                minSize=(60, 60), flags=cv2.CASCADE_SCALE_IMAGE)

            if len(faces) == 0 and self.cascade_alt is not None:
                faces = self.cascade_alt.detectMultiScale(
                    gray, scaleFactor=1.05, minNeighbors=3, minSize=(60, 60))

            self.face_detected = len(faces) > 0

            for (x, y, w, h) in faces:
                cv2.rectangle(display, (x, y), (x+w, y+h), (0, 220, 80), 2)
                cv2.putText(display, "ADMIN", (x, y - 8),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.65, (0, 220, 80), 2)

            self.frame = display
            time.sleep(0.03)

    def stop(self):
        self.running = False
        if self.cap:
            self.cap.release()


# ══════════════════════════════════════════════
#  VOICE LISTENER
# ══════════════════════════════════════════════
class VoiceListener:
    def __init__(self, result_queue):
        self.q       = result_queue
        self.running = False
        if SPEECH_OK:
            self.recognizer = sr.Recognizer()
            self.recognizer.energy_threshold         = 300
            self.recognizer.dynamic_energy_threshold = True
            self.recognizer.pause_threshold          = 0.8

    def start(self):
        if not SPEECH_OK:
            return
        self.running = True
        threading.Thread(target=self._loop, daemon=True).start()

    def _loop(self):
        with sr.Microphone() as source:
            self.recognizer.adjust_for_ambient_noise(source, duration=1)
            while self.running:
                try:
                    audio = self.recognizer.listen(source, timeout=4, phrase_time_limit=30)
                    text  = self.recognizer.recognize_google(audio)
                    self.q.put(("voice", text))
                except sr.WaitTimeoutError:
                    pass
                except sr.UnknownValueError:
                    pass
                except Exception as e:
                    self.q.put(("error", str(e)))

    def stop(self):
        self.running = False


# ══════════════════════════════════════════════
#  MAIN GUI
# ══════════════════════════════════════════════
class App(tk.Tk):
    BG     = "#080c10"
    PANEL  = "#0d1117"
    BORDER = "#21262d"
    ACCENT = "#00d4aa"
    BLUE   = "#58a6ff"
    GREEN  = "#3fb950"
    WARN   = "#d29922"
    RED    = "#f85149"
    TEXT   = "#cdd9e5"
    MUTED  = "#768390"
    FONT   = ("Consolas", 11)
    FONT_B = ("Consolas", 11, "bold")

    def __init__(self):
        super().__init__()
        self.title("AI Interactive System  -  Ollama / llama3")
        self.geometry("1020x700")
        self.minsize(800, 550)
        self.configure(bg=self.BG)

        self.camera   = Camera()
        self.msg_q    = queue.Queue()
        self.voice    = VoiceListener(self.msg_q)
        self.busy     = False

        # Conversation history sent to the model each turn
        self.history  = [{"role": "system", "content": SYSTEM_PROMPT}]

        self._build_ui()
        self._start_services()
        self.after(100, self._poll_queue)
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    # ── UI ────────────────────────────────────
    def _build_ui(self):
        hdr = tk.Frame(self, bg=self.PANEL, height=54)
        hdr.pack(fill=tk.X)
        hdr.pack_propagate(False)

        tk.Label(hdr, text="AI INTERACTIVE SYSTEM",
                 font=("Consolas", 15, "bold"), bg=self.PANEL, fg=self.ACCENT
                 ).pack(side=tk.LEFT, padx=18, pady=10)
        tk.Label(hdr, text="Powered by Ollama llama3  |  Fully Local  |  No Internet",
                 font=("Consolas", 9), bg=self.PANEL, fg=self.MUTED
                 ).pack(side=tk.LEFT, pady=16)

        self.mic_lbl = tk.Label(hdr, text="MIC: --", font=("Consolas", 9, "bold"),
                                bg=self.PANEL, fg=self.MUTED)
        self.mic_lbl.pack(side=tk.RIGHT, padx=8)

        self.cam_lbl = tk.Label(hdr, text="CAM: --", font=("Consolas", 9, "bold"),
                                bg=self.PANEL, fg=self.MUTED)
        self.cam_lbl.pack(side=tk.RIGHT, padx=8)

        tk.Frame(self, bg=self.BORDER, height=1).pack(fill=tk.X)

        body = tk.Frame(self, bg=self.BG)
        body.pack(fill=tk.BOTH, expand=True, padx=14, pady=10)

        # Left: conversation
        left = tk.Frame(body, bg=self.BG)
        left.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        tk.Label(left, text="CONVERSATION", font=self.FONT_B,
                 bg=self.BG, fg=self.MUTED).pack(anchor=tk.W, pady=(0, 4))

        chat_frame = tk.Frame(left, bg=self.BORDER)
        chat_frame.pack(fill=tk.BOTH, expand=True)
        inner = tk.Frame(chat_frame, bg=self.PANEL)
        inner.pack(fill=tk.BOTH, expand=True, padx=1, pady=1)

        self.chat = scrolledtext.ScrolledText(
            inner, font=self.FONT, bg=self.PANEL, fg=self.TEXT,
            relief=tk.FLAT, padx=12, pady=10, wrap=tk.WORD,
            state=tk.DISABLED, selectbackground="#264f78",
            insertbackground=self.ACCENT)
        self.chat.pack(fill=tk.BOTH, expand=True)

        self.chat.tag_config("you",      foreground=self.BLUE,  font=("Consolas", 11, "bold"))
        self.chat.tag_config("system",   foreground=self.ACCENT,font=("Consolas", 11, "bold"))
        self.chat.tag_config("response", foreground=self.TEXT)
        self.chat.tag_config("muted",    foreground=self.MUTED)
        self.chat.tag_config("warn",     foreground=self.WARN)

        inp_row   = tk.Frame(left, bg=self.BG)
        inp_row.pack(fill=tk.X, pady=(8, 0))
        inp_bg    = tk.Frame(inp_row, bg=self.BORDER)
        inp_bg.pack(side=tk.LEFT, fill=tk.X, expand=True)
        inp_inner = tk.Frame(inp_bg, bg="#161b22")
        inp_inner.pack(fill=tk.X, padx=1, pady=1)

        self.entry = tk.Entry(inp_inner, font=self.FONT, bg="#161b22", fg=self.TEXT,
                              insertbackground=self.ACCENT, relief=tk.FLAT,
                              highlightthickness=0)
        self.entry.pack(fill=tk.X, padx=10, pady=7)
        self.entry.bind("<Return>", lambda e: self._send_text())

        self.send_btn = tk.Button(inp_row, text="SEND", font=self.FONT_B,
                                  bg=self.ACCENT, fg="#000", activebackground="#00b894",
                                  relief=tk.FLAT, padx=16, pady=6,
                                  cursor="hand2", command=self._send_text)
        self.send_btn.pack(side=tk.LEFT, padx=(8, 0))

        tk.Button(inp_row, text="CLEAR", font=self.FONT_B,
                  bg=self.PANEL, fg=self.MUTED, activebackground=self.BORDER,
                  relief=tk.FLAT, padx=12, pady=6,
                  cursor="hand2", command=self._clear_chat
                  ).pack(side=tk.LEFT, padx=(6, 0))

        # divider
        tk.Frame(body, bg=self.BORDER, width=1).pack(side=tk.LEFT, fill=tk.Y, padx=10)

        # Right: camera
        right = tk.Frame(body, bg=self.BG, width=280)
        right.pack(side=tk.LEFT, fill=tk.Y)
        right.pack_propagate(False)

        tk.Label(right, text="CAMERA FEED", font=self.FONT_B,
                 bg=self.BG, fg=self.MUTED).pack(anchor=tk.W, pady=(0, 4))

        cam_border = tk.Frame(right, bg=self.BORDER)
        cam_border.pack(fill=tk.X)
        self.cam_canvas = tk.Canvas(cam_border, width=256, height=192,
                                    bg="#000", highlightthickness=0)
        self.cam_canvas.pack(padx=1, pady=1)
        self._draw_cam_placeholder()

        self.face_status = tk.Label(right, text="NO FACE DETECTED",
                                    font=("Consolas", 9, "bold"),
                                    bg=self.BG, fg=self.RED)
        self.face_status.pack(pady=(4, 0), anchor=tk.W)

        self.mic_status = tk.Label(right, text="Mic: Initializing...",
                                   font=("Consolas", 9), bg=self.BG, fg=self.MUTED)
        self.mic_status.pack(pady=2, anchor=tk.W)

        # model indicator
        tk.Frame(right, bg=self.BORDER, height=1).pack(fill=tk.X, pady=8)
        tk.Label(right, text="MODEL", font=self.FONT_B,
                 bg=self.BG, fg=self.MUTED).pack(anchor=tk.W)
        tk.Label(right, text="llama3 (local)", font=("Consolas", 10),
                 bg=self.BG, fg=self.GREEN).pack(anchor=tk.W, pady=2)
        tk.Label(right, text="via Ollama  :11434", font=("Consolas", 9),
                 bg=self.BG, fg=self.MUTED).pack(anchor=tk.W)

        tk.Frame(right, bg=self.BORDER, height=1).pack(fill=tk.X, pady=8)
        tk.Label(right, text="QUICK COMMANDS", font=self.FONT_B,
                 bg=self.BG, fg=self.MUTED).pack(anchor=tk.W)

        quick_cmds = [
            ("Can you see me?",                      self.BLUE),
            ("Who am I?",                            self.GREEN),
            ("Alice and Bob desert survival",        self.WARN),
            ("What is 144 divided by 12 plus 8?",   self.ACCENT),
        ]
        for cmd, color in quick_cmds:
            tk.Button(right, text=cmd, font=("Consolas", 9),
                      bg=self.PANEL, fg=color, activebackground=self.BORDER,
                      relief=tk.FLAT, anchor=tk.W, padx=8, pady=5,
                      cursor="hand2",
                      command=lambda c=cmd: self._quick_send(c)
                      ).pack(fill=tk.X, pady=1)

        tk.Frame(self, bg=self.BORDER, height=1).pack(fill=tk.X)
        footer = tk.Frame(self, bg=self.PANEL, height=26)
        footer.pack(fill=tk.X)
        footer.pack_propagate(False)
        tk.Label(footer,
                 text="Press Enter or click SEND  |  Speak naturally into your mic  |  ollama serve must be running",
                 font=("Consolas", 8), bg=self.PANEL, fg=self.MUTED
                 ).pack(side=tk.LEFT, padx=14, pady=4)

    # ── services ─────────────────────────────
    def _start_services(self):
        if CAM_OK:
            self.camera.start()
            self.cam_lbl.config(text="CAM: ON", fg=self.GREEN)
            self._update_camera()
        else:
            self.cam_lbl.config(text="CAM: MISSING", fg=self.RED)
            self._log_system("opencv not installed. Run: pip install opencv-python", "warn")

        if SPEECH_OK:
            self.voice.start()
            self.mic_lbl.config(text="MIC: ON", fg=self.GREEN)
            self.mic_status.config(text="Mic: Listening...", fg=self.GREEN)
        else:
            self.mic_lbl.config(text="MIC: MISSING", fg=self.RED)
            self.mic_status.config(text="Mic: Not available", fg=self.RED)
            self._log_system("SpeechRecognition not installed. Run: pip install SpeechRecognition pyaudio", "warn")

        if not REQUESTS_OK:
            self._log_system("requests not installed. Run: pip install requests", "warn")

        self._log_system(
            "System online. Using llama3 via Ollama.\n"
            "Make sure ollama is running:  ollama serve", "muted")

    def _update_camera(self):
        if not CAM_OK or not self.camera.running:
            return
        frame = self.camera.frame
        if frame is not None:
            try:
                from PIL import Image, ImageTk
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                img   = Image.fromarray(frame_rgb).resize((256, 192))
                photo = ImageTk.PhotoImage(img)
                self.cam_canvas.create_image(0, 0, anchor=tk.NW, image=photo)
                self.cam_canvas._photo = photo
            except Exception:
                pass

            if self.camera.face_detected:
                self.face_status.config(text="FACE DETECTED", fg=self.GREEN)
            else:
                self.face_status.config(text="NO FACE DETECTED", fg=self.RED)

        self.after(80, self._update_camera)

    def _draw_cam_placeholder(self):
        self.cam_canvas.create_rectangle(0, 0, 256, 192, fill="#000")
        self.cam_canvas.create_text(128, 96, text="No Camera Feed",
                                    fill=self.MUTED, font=("Consolas", 10),
                                    justify=tk.CENTER)

    # ── queue polling ─────────────────────────
    def _poll_queue(self):
        try:
            while True:
                kind, data = self.msg_q.get_nowait()
                if kind == "voice":
                    self._process_input(data, source="You (voice)")
                elif kind == "error":
                    self._log_system("Mic error: " + data, "warn")
        except queue.Empty:
            pass
        self.after(200, self._poll_queue)

    # ── input handling ────────────────────────
    def _send_text(self):
        if self.busy:
            return
        text = self.entry.get().strip()
        if not text:
            return
        self.entry.delete(0, tk.END)
        self._process_input(text, source="You")

    def _quick_send(self, cmd):
        if self.busy:
            return
        self.entry.delete(0, tk.END)
        self.entry.insert(0, cmd)
        self._send_text()

    def _clear_chat(self):
        self.chat.config(state=tk.NORMAL)
        self.chat.delete("1.0", tk.END)
        self.chat.config(state=tk.DISABLED)
        # Reset history but keep system prompt
        self.history = [{"role": "system", "content": SYSTEM_PROMPT}]

    def _process_input(self, text, source="You"):
        if self.busy:
            return
        self.busy = True
        self.send_btn.config(state=tk.DISABLED, text="...")

        # Build user message - inject camera state for relevant questions
        user_content = text
        face_keywords = re.search(r'\b(see me|visible|camera|who am i|identify)\b', text.lower())
        if face_keywords:
            face_state = "FACE DETECTED" if (CAM_OK and self.camera.face_detected) else "NO FACE DETECTED"
            user_content = text + "\n[Camera status: " + face_state + "]"

        self.history.append({"role": "user", "content": user_content})

        self._append("\n" + source + ":  ", "you")
        self._append(text + "\n", "response")
        self._append("System:  ", "system")

        # Stream response in background thread
        def run():
            buffer = []

            def on_chunk(chunk):
                buffer.append(chunk)
                self.after(0, self._append, chunk, "response")

            full = query_ollama(self.history, on_chunk)
            self.history.append({"role": "assistant", "content": full})
            self.after(0, self._finish)

        threading.Thread(target=run, daemon=True).start()

    def _finish(self):
        self._append("\n", "response")
        self.busy = False
        self.send_btn.config(state=tk.NORMAL, text="SEND")

    def _append(self, text, tag="response"):
        self.chat.config(state=tk.NORMAL)
        self.chat.insert(tk.END, text, tag)
        self.chat.see(tk.END)
        self.chat.config(state=tk.DISABLED)

    def _log_system(self, text, tag="muted"):
        self._append("\n[SYSTEM]  " + text + "\n", tag)

    def _on_close(self):
        self.camera.stop()
        self.voice.stop()
        self.destroy()


if __name__ == "__main__":
    App().mainloop()